# Generated by Django 4.2.30 on 2026-04-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.TextField()),
                ('departmentHead', models.TextField(blank=True, null=True)),
                ('specialisation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.TextField()),
                ('developmentFocusArea', models.TextField(blank=True, null=True)),
                ('keySkillsAndTechnologies', models.TextField(blank=True, null=True)),
                ('agilePractices', models.TextField(blank=True, null=True)),
                ('numberOfConcurrentProjects', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organisation.department')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencyType', models.TextField(blank=True, null=True)),
                ('sourceTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='organisation.team')),
                ('targetTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='organisation.team')),
            ],
            options={
                'unique_together': {('sourceTeam', 'targetTeam')},
            },
        ),
    ]
