# Generated by Django 4.2.30 on 2026-04-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.TextField()),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.IntegerField(primary_key=True, serialize=False)),
                ('teamName', models.TextField()),
                ('developmentFocusArea', models.TextField(blank=True, null=True)),
                ('jiraBoardLink', models.TextField(blank=True, null=True)),
                ('keySkillsAndTechnologies', models.TextField(blank=True, null=True)),
                ('softwareOwnedAndEvolved', models.TextField(blank=True, null=True)),
                ('versioningApproaches', models.TextField(blank=True, null=True)),
                ('wikiSearchTerms', models.TextField(blank=True, null=True)),
                ('dailyStundupTimeAndLink', models.TextField(blank=True, null=True)),
                ('agilePractices', models.TextField(blank=True, null=True)),
                ('wikiLink', models.TextField(blank=True, null=True)),
                ('numberOfConcurrentProjects', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencyType', models.TextField(blank=True, null=True)),
                ('sourceTeam', models.ForeignKey(db_column='sourceTeamID', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='organisation.team')),
                ('targetTeam', models.ForeignKey(db_column='targetTeamID', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='organisation.team')),
            ],
            options={
                'db_table': 'TeamDependency',
                'unique_together': {('sourceTeam', 'targetTeam')},
            },
        ),
    ]
