# Generated by Django 4.2.30 on 2026-04-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('engineerID', models.IntegerField(primary_key=True, serialize=False)),
                ('engineerName', models.TextField(blank=True, null=True)),
                ('engineerEmail', models.TextField(blank=True, null=True)),
                ('engineerExpertise', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Engineer',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='teamdependency',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamdependency',
            name='sourceTeam',
            field=models.ForeignKey(db_column='sourceTeamID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outgoing_dependencies', serialize=False, to='organisation.team'),
        ),
        migrations.AlterModelTable(
            name='teamdependency',
            table='Team_Dependency',
        ),
    ]
