# Generated by Django 4.2.30 on 2026-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_engineer_remove_teamdependency_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditLogID', models.AutoField(primary_key=True, serialize=False)),
                ('editEntityType', models.TextField(blank=True, null=True)),
                ('editActionType', models.TextField(blank=True, null=True)),
                ('editTimestamp', models.TextField(blank=True, null=True)),
                ('userID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Audit_Log',
                'managed': False,
            },
        ),
    ]
