# Generated by Django 4.2.30 on 2026-04-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('scheduleEventID', models.IntegerField(db_column='scheduleEventID', primary_key=True, serialize=False)),
                ('scheduleEventTitle', models.TextField(blank=True, db_column='scheduleEventTitle', null=True)),
                ('scheduleEventDate', models.TextField(blank=True, db_column='scheduleEventDate', null=True)),
                ('scheduleEventTime', models.TextField(blank=True, db_column='scheduleEventTime', null=True)),
                ('scheduleEventDescription', models.TextField(blank=True, db_column='scheduleEventDescription', null=True)),
                ('scheduleEventPlatform', models.TextField(blank=True, db_column='scheduleEventPlatform', null=True)),
            ],
            options={
                'db_table': 'Schedule_Event',
            },
        ),
    ]
