# Generated by Django 4.2.30 on 2026-04-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='messageContent',
            field=models.TextField(blank=True, db_column='messageContent', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='messageID',
            field=models.IntegerField(db_column='messageID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='messageTitle',
            field=models.TextField(blank=True, db_column='messageTitle', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='messageType',
            field=models.TextField(blank=True, db_column='messageType', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='teamID',
            field=models.IntegerField(blank=True, db_column='teamID', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='userID',
            field=models.IntegerField(blank=True, db_column='userID', null=True),
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
